# Generated by Django 5.1.1 on 2024-09-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='assigned_to',
        ),
    ]
