# Generated by Django 5.1.1 on 2024-09-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='done',
            field=models.CharField(choices=[('doing', 'Em andamento'), ('done', 'Concluída'), ('missing', 'Pendente')], max_length=7),
        ),
    ]
