# Generated by Django 5.1.1 on 2024-09-08 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='tarefas_colaborativas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='done',
            field=models.CharField(choices=[('doing', 'Em andamento'), ('done', 'Concluída'), ('pending', 'Pendente')], max_length=7),
        ),
    ]
