# Generated by Django 5.1.1 on 2024-09-08 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefa_colaboradores_alter_tarefa_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='tarefas_compartilhadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
