# Generated by Django 5.1.1 on 2024-09-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_tarefa_vencimento_alter_tarefa_colaboradores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='vencimento',
        ),
    ]
