# Generated by Django 5.1.1 on 2024-09-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_remove_tarefa_colaboradores_remove_tarefa_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_de_entrega',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
